### ISSUE TITLE
Startup Project

### ISSUE THREAD

**Issue by annettaws** [Braunson/laravel-coreui-vue#10]
Hi,
I picked up your project and i'm run on Homestead.
I run composer install and npm install. php artisan migrate ad db:seed (nothing it was seeded)
But when i visit the site i received this message:
No input file specified..

Can you help me?

**Comment by dicarlosystems** [comment]
Did you make sure to copy .env.example to .env and update for your environment?  You also need to run npm run dev (or prod) to generate the assets.

**Comment by Braunson** [comment]
@annettaws Did you see @dicarlosystems's message? Can you report back on this?

**Comment by Braunson** [comment]
Closing due to non-response, assuming this was wrapped up. I was unable to re-create the issue and it sounds specific to the user's environment.
