### ISSUE TITLE
question

### ISSUE THREAD

**Issue by luoxulx** [Braunson/laravel-coreui-vue#16]
I installed vue-i18n and modified your directory structure,  then added the language pack.now some errors had happened.
![image](https://user-images.githubusercontent.com/35016570/40221394-f2e37462-5aae-11e8-9007-ed06c604987c.png)
I'm sure my configuration file is correct.
but in the _nav.js, i still can't use 'this.$t(xxx)' to replace the name of items,console tips: Uncaught TypeError: this.$t is not a function,How do i fix it? And Thanks very much.

**Comment by luoxulx** [comment]
In html, language packs can be translated correctly, but in a menu type file such as _nav.js, they cannot be translated correctly. I don't know where it is.
![image](https://user-images.githubusercontent.com/35016570/40222559-7cbfa0e0-5ab2-11e8-844b-9b77682048f8.png)
![image](https://user-images.githubusercontent.com/35016570/40222582-8ffb1ff4-5ab2-11e8-98f9-df61d8606237.png)

**Comment by Braunson** [comment]
@luoxulx Since this isn't directly related to this repo I'll be closing the issue. 

Have you imported/exported the vue-i18n in `app.js`? Have you opened a ticket on `vue-i18n`'s repo?
