### ISSUE TITLE
Composer install is not working

### ISSUE THREAD

**Issue by hkmsadek** [Braunson/laravel-coreui-vue#17]
When I do `composer install` I get this 

`composer install
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 71 installs, 0 updates, 0 removals
  - Installing mrholek/coreui-free-bootstrap-admin-template (dev-24d9a64 24d9a64): 
`

and after sometimes, it fails with timeout issue.

Any idea why it's happening?

**Comment by Braunson** [comment]
@hkmsadek Composer timing out isn't specifically related to this repo but try running this command to force composer to get from the source (not cache).

`composer install --prefer-dist`

Is there any other errors Composer throws out?
