### ISSUE TITLE
Basic setup

### ISSUE THREAD

**Issue by srlopez** [Braunson/laravel-coreui-vue#3]
Hi Brauson!
Great job! and really Thanks for this.

I want to start the project, but after the basic setup steps, it seems to me that something is not doing right.
After cloning the project:
`$ composer install`
  And I get an error that does not matter since I see that the components are copied in assests.
then:

>  Package operations: 29 installs, 0 updates, 0 removals
>    - Installing mrholek/coreui-free-bootstrap-admin-template (1.0.0): Downloading (failed)    Failed to download mrholek/CoreUI-Free-Bootstrap-Admin-Template from dist: The "https://api.github.com/repos/mrholek/CoreUI-Free-Bootstrap-Admin-Template/zipball/tags/1.0.0" file could not be downloaded (HTTP/1.1 302 Found)
>      Now trying to download from source
>    - Installing mrholek/coreui-free-bootstrap-admin-template (1.0.0): Cloning tags/1.0.0
>      tags/1.0.0 is gone (history was rewritten?)
> 
>                                                                                       
>   [RuntimeException]                                                                  
>   Failed to execute git checkout 'tags/1.0.0' -- && git reset --hard 'tags/1.0.0' --  
>   fatal: invalid reference: tags/1.0.0   

          

```
$ npm install
$ npm run dev
```
and the
`$ php artisan serve`, but ...

> Warning: require(/source/laravel-coreui-vue/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /source/laravel-coreui-vue/bootstrap/autoload.php on line 17
> 
> Fatal error: require(): Failed opening required '/source/laravel-coreui-vue/bootstrap/../vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /source/laravel-coreui-vue/bootstrap/autoload.php on line 17

Line 17 is :
`require __DIR__.'/../vendor/autoload.php';`

Have to point to another place?

If i copy teh file to 'vendor then...

> Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 130968 bytes) in /source/laravel-coreui-vue/vendor/autoload.php on line 17

Or what can I be forgetting in setup?
How can continue?

Thanks in advance

**Comment by Braunson** [comment]
It seems like the original author has removed tags from their project. I'll get back to you on this soon!

**Comment by jiangdi0924** [comment]
Hi Brauson!

i find zhe same question

Downloading (failed)    Failed to download mrholek/CoreUI-Free-Bootstrap-Admin-Template from dist: The "https://api.github.com/repos/mrholek/CoreUI-Free-Bootstrap-Admin-Template/zipball/tags/1.0.0" file could not be dow
nloaded (HTTP/1.1 302 Found)
    Now trying to download from source

**Comment by wissemchiha** [comment]
Hi,
try to update composer.json with

```
{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=5.6.4",
        "laravel/framework": "5.4.*",
        "laravel/tinker": "~1.0",
        "mrholek/CoreUI-Free-Bootstrap-Admin-Template": "1.0.0"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~5.7"
    },
    "repositories": [
        {
            "type": "package",
            "package": {
                "name": "mrholek/CoreUI-Free-Bootstrap-Admin-Template",
                "version": "1.0.0",
                "dist": {
                    "url": "https://github.com/mrholek/CoreUI-Free-Bootstrap-Admin-Template/archive/master.zip",
                    "type": "zip"
                }
             
            }
        }
    ],
    "autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "scripts": {
        "post-root-package-install": [
            "php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "php artisan key:generate"
        ],
        "post-install-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postInstall",
            "php artisan optimize"
        ],
        "post-update-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postUpdate",
            "php artisan optimize"
        ]
    },
    "config": {
        "preferred-install": "dist",
        "sort-packages": true,
        "optimize-autoloader": true
    }
}
```
and run 
composer update, composer install

**Comment by jiangdi0924** [comment]
thank you very much

2017-07-24 22:15 GMT+08:00 wissem <notifications@github.com>:

**Comment by jnryu87** [comment]
I have downloaded it and also had issue with git repository.
If anyone is not good with Composer,
delete, mrholek part in composer in require and repository.
If you have composer.lock, delete it too. And then composer install( probably for basic Laravel 5.4 install).
Create folder manually, in my case
-> C:\xampp\htdocs\projects\laravel-coreui-vue-master\vendor\mrholek
Download .zip from https://github.com/mrholek/CoreUI-Free-Bootstrap-Admin-Template
unzip it and just send whole folder which has contents. It works fine with me !

**Comment by Braunson** [comment]
Thanks, this has been resolved and pushed up!
