### ISSUE TITLE
Laravel 5.5 support (upcoming)

### ISSUE THREAD

**Issue by dicarlosystems** [Braunson/laravel-coreui-vue#6]
Hi,

Just a question, wondering what your plans are for the upcoming Laravel 5.5 release, given that it's an LTS version?

Cheers,
Chris

**Comment by Braunson** [comment]
Hi @dicarlosystems,

Yes I intend to update it to Laravel 5.5 once it's released. This is only a boilerplate to start with Laravel & CoreUI Vue.
