### ISSUE TITLE
Whoops, looks like something went wrong.

### ISSUE THREAD

**Issue by srlopez** [Braunson/laravel-coreui-vue#7]
Thanks very much for your work Braunson.

After `git clone` your repo, then run `composer install`, then `artisan serve`, and go to the browser.
The only message is `Whoops, looks like something went wrong.`

Thanks for your help.

**Comment by dicarlosystems** [comment]
What does the stack trace say?  Did you update your .env file?

**Comment by ljonka** [comment]
maybe this will help: https://github.com/Braunson/laravel-coreui-vue/pull/8

**Comment by Braunson** [comment]
Merging PR, should resolve this issue, if it doesn't let me know.
